### PR TITLE
document trade protocol messaging

### PR DESCRIPTION
**Pull request by woodser**

### CODE REVIEW

**Comment by erciccione** [comment]
Since we have multiple files related to the trade protocol, maybe we could add them to a dedicated folder like `docs/trade_protocol`

**Comment by woodser** [comment]
I moved these docs to a folder per your suggestion and linked to network messages documentation in trade-protocol.md.

**Review by erciccione — APPROVED** [review]

**Review by erciccione — APPROVED** [review]

**Comment by HoverHalver** [comment]
The "arbitrator" is mentioned in the trade protocol in steps 4, 9, 10, 14 and 17.
But @woodser told me (on Matrix) that in fact steps 4, 9, 10, 14 should be achieved automatically.
I think that this should appear clearly in the trade protocol.

**Comment by woodser** [comment]
> The "arbitrator" is mentioned in the trade protocol in steps 4, 9, 10, 14 and 17.
> But @woodser told me (on Matrix) that in fact steps 4, 9, 10, 14 should be achieved automatically.
> I think that this should appear clearly in the trade protocol.

I added a note that all steps involving the arbitrator are automatic except resolving disputes.

**Pull request merged**
