### PR TITLE
Solution to issue #531

### PR DESCRIPTION
**Pull request by niyid**
Solves issue #531

### CODE REVIEW

**Comment by woodser** [comment]
Great. I'm working on applying cleanup which we'll be able to rebase on a [change to the changePassword() api](https://github.com/haveno-dex/haveno/pull/562).

**Comment by woodser** [comment]
I opened a PR against your branch with cleanup: https://github.com/Hypothenus/haveno-531/pull/1

**Comment by woodser** [comment]
@niyid I've merged the update to the `changePassword()` API.

Please review and merge my PR: https://github.com/Hypothenus/haveno-531/pull/1

And please squash and rebase your PR on master. I expect the only merge conflict will be updates to `CoreAccountService.changePassword()`.

**Comment by woodser** [comment]
Looks like the merge was done incorrectly. The changes from https://github.com/Hypothenus/haveno-531/pull/1 are reverted with your commits after.

You should be able to `git reset --hard 1a72b25` then rebase that onto current master, which I think should result in only one merge conflict in CoreAccountService.java, which needs resolved with the latest in my PR.

**Comment by niyid** [comment]
> Looks like the merge was done incorrectly. The changes from [Hypothenus#1](https://github.com/Hypothenus/haveno-531/pull/1) are reverted with your commits after.
> 
> You should be able to `git reset --hard 1a72b25` then rebase that onto current master, which I think should result in only one merge conflict in CoreAccountService.java, which needs resolved with the latest in my PR.
> 
> Then the result can be squashed and there are no merge conflicts with current master.

Here is the result after resolving the merge conflict in CoreAccountService.java:

https://github.com/haveno-dex/haveno/actions/runs/4271201960/jobs/7435508645

**Comment by woodser** [comment]
> I think you know exactly what you want to achieve from this; I don't (and which repository you refer to as master - either on Hypothenus or origin). The main thing is this PR is tested and works and has satisfied the requirement.

Very well. I've opened a PR with our squashed changes: https://github.com/haveno-dex/haveno/pull/567

**Pull request closed without merging**
