### PR TITLE
Make offers filterable via offer ID or Node address

### PR DESCRIPTION
**Pull request by wp07e**
#1094 

image

I tested it using custom search of ID or node address by itself and in addition to combining it with other filter criteria such as "Choose Currency" and "Choose payment method" and seems to work correctly.

### CODE REVIEW

**Comment by XMRfamily** [comment]
Nice job

**Comment by wp07e** [comment]
@XMRfamily it was easiest one 🤣

**Comment by XMRfamily** [comment]
> @XMRfamily it was easiest one 🤣

I'll send you 100 wow send walley addy

**Comment by wp07e** [comment]
@XMRfamily uhhhh... wow? whats that? 🤣

**Comment by XMRfamily** [comment]
> @XMRfamily uhhhh... wow? whats that? 🤣

It's meme fork of monero, you can have wallet on cake 🎂

**Comment by woodser** [comment]
The filter box needs to conform to existing UI standards:

image

- Should appear exactly like the "Choose currency" and "Choose payment method" inputs with a top label, "Filter"
- Input box height same height as "Choose currency" input, with placeholder text, like "Offer ID, address ..."
- Remove the line which is underneath it

image

- UI elements have been grouped in the center here. Revert to current behavior

**Comment by wp07e** [comment]
@XMRfamily Ahh I see thank you so much but I definitely am not in need of crypto 😈. But instead if you can donate that .05XMR to a bounty for someone else that would be awesome!

**Comment by wp07e** [comment]
@woodser hummm... I didn't realize it was that bad! 😱

**Comment by XMRfamily** [comment]
> @XMRfamily Ahh I see thank you so much but I definitely am not in need of crypto 😈. But instead if you can donate that .05XMR to a bounty for someone else that would be awesome!

https://bounties.monero.social/posts/128/100-150m-mvp-tor-based-mobile-web-application-to-interact-with-ledger-nano-x-and-haveno

**Comment by wp07e** [comment]
@XMRfamily I think that one has enough coin already 🤣 but thank you

**Comment by wp07e** [comment]
@woodser All of these "AutoToolTip..." UI components I am not sure where they are being used can you check 1 of them and see if they have the same behavior as before? That is my only concern with the changes I made

**Comment by wp07e** [comment]
@woodser I think good to go now

**Comment by woodser** [comment]
And actually let's remove the placeholder text "Offer, address...", to see what it looks like and be consistent with the other filter boxes.

**Pull request merged**
