### PR TITLE
Do not add payment account currencies by default

### PR DESCRIPTION
**Pull request by wp07e**
This is a re-follow-up to https://github.com/haveno-dex/haveno/pull/1066

Well... that was fun. Turns out I am an Idiot!

But, again, at least I learned more about the app! So can't complain too much.

And, I love this app so much 💗

### CODE REVIEW

**Comment by woodser** [comment]
This still seems weird. It's only a UI thing to unselect the checkboxes while creating the payment account. I wouldn't expect any changes to the backend account code.

**Comment by wp07e** [comment]
I am not super familiar with Java (any more) but the way the checkboxes are instantiated, its impossible to uncheck them such that he checkboxes are unselected only on the first load. Unless there is some CSS property you can set on the checkboxes parent, I didn't see any other way. If you can take a quick look and you find a better way I would be happy to gain some knowledge. 

The checkboxes are created in the function:
`
void fillUpFlowPaneWithCurrencies(boolean isEditable, FlowPane flowPane,
                                      TradeCurrency e, PaymentAccount paymentAccount)
`

**Comment by woodser** [comment]
I or someone else would need to look into it, but we wouldn't want to remove adding those supported currencies from the accounts.

**Comment by wp07e** [comment]
Well they are not removed. They are only removed from the "available" currencies until you create the payment account and start adding some currencies. Then they will be available to use in the app.

Nothing is deleted. I ran it already seem to be working fine. What part is not working for you?

**Comment by wp07e** [comment]
Trade currencies for each payment type are defined in 

`
public static final List<TradeCurrency> SUPPORTED_CURRENCIES
`
which I did not modify. I only deleted whats currencies are available to the account type until you add them youself.

**Comment by wp07e** [comment]
So are you not going to accept this pull request? I'm telling you this is the most efficient way to uncheck these checkboxes with only 9 lines of code deleted.

This issue is pretty important so unless someone else want to try to resolve before the next release, I think we should go with my version since it works perfectly fine.

**Comment by woodser** [comment]
Ok maybe that works, simply not adding them by default. I will test it.

**Comment by wp07e** [comment]
Hey if your upset because you had to test it three times I get it. I'll do my part to test better in the future. 

But let's all continue to work together to make Haveno a better app! :)

**Comment by woodser** [comment]
Please undo the removal from the SWIFT payment account. This account type supports all fiat currencies, and the UI does not display checkboxes. The final currency is determined when the offer is made.

**Pull request merged**
