### PR TITLE
Fixing some words displayStrings_cs.properties

### PR DESCRIPTION
**Pull request by slrslr**
It is pretty common that the node (a computer/server) is translated as uzel in czech language.
"Cryptoy" translation is a nonsense, for a cryptocurrency is used "kryptoměna" translation.

I have noticed that some variables like "shared.yourDepositTransactionId" are missing in this czech language file, but exist in original english file. As a layman user, I do not know about any convenient and fast way to merge all missing lines into a czech file so it is at a proper spot, not all at the end of file and so i can easily find and translate the merged lines. If you can not tell me the steps to do it ( I am on Linux), maybe do it yourself and i will then go through the CS file, find english strings and translate these.

### CODE REVIEW

**Comment by slrslr** [comment]
How I could avoid https://github.com/haveno-dex/haveno/actions/runs/12166479027 or it was necessary to run like half hour and generate hundreds of MB data for each smallest text file modification?

**Comment by woodser** [comment]
> How I could avoid https://github.com/haveno-dex/haveno/actions/runs/12166479027 or it was necessary to run like half hour and generate hundreds of MB data for each smallest text file modification?

Yeah it runs the complete build including installers.

**Comment by slrslr** [comment]
> How I could avoid https://github.com/haveno-dex/haveno/actions/runs/12166479027 or it was necessary to run like half hour and generate hundreds of MB data for each smallest text file modification?

Regarding this HuggingChat AI suggests this to a maintainer of this repo:

1. Talk to the maintainers: Reach out to the project maintainers and ask if they can optimize the CI/CD pipeline or provide guidance on how to minimize the build time.

2. Use a GitHub Actions feature: GitHub Actions provides a feature called "Workflow optimization" that can help reduce the number of builds and tests. You can ask the maintainers to enable this feature.

and this to a PR submitter:

1. Use a draft pull request: If you're not sure about the impact of your changes, consider creating a draft pull request. This will allow you to test the CI/CD pipeline without triggering a full build.

I am unsure if draft request is visible to the maintainer and he is notified about it.

> merge all missing lines into a czech file

I guess you have no time for this since you have not replied.

**Comment by slrslr** [comment]
Since @woodser ignored the second paragraph in my initial post of this PR, I have spent some time in getting a [Linux bash script](https://drive.proton.me/urls/53FF044SN8#2mrZsix4SxIw) which helped me to partly synchronize outdated Haveno czech language file with english original (tens of strings were missing, many out of order and others were orphan) and then i have spend around 8 hours manually fixing issues resulting in [decent quality czech file. Please use it](https://bin.disroot.org/?4c5717992bf8751f#GdWmAnQBUqspQVe6gQ9h425LqnXdkVcRsgjbMif1GKmv) instead of a current file https://github.com/haveno-dex/haveno/blob/master/core/src/main/resources/i18n/displayStrings_cs.properties
And please consider a good practice of using translation service https://github.com/haveno-dex/haveno/issues/1506

**Comment by woodser** [comment]
Please submit a PR with the improvements to the Czech translation file. Thanks.

**Pull request merged**
