### PR TITLE
Now onWithdraw() runs in a separate thread while displaying progress …

### LINKED ISSUE #853: Application hangs while creating withdraw tx [0.25 XMR]
Currently, the application hangs while creating a withdraw tx from Funds > Send Funds.

image

On tor especially, creating the tx can take 30-60 seconds, so the application is unresponsive during this time.

This issue requests moving the processing off the main thread so the application does not hang, and adding a spinny wheel so the user knows stuff is happening, similar to the Payment Sent and Payment Received confirmation buttons.

### PR DESCRIPTION
**Pull request by niyid**
Now onWithdraw() runs in a separate thread while displaying progress bar. Fixes #853

### CODE REVIEW

**Comment by niyid** [comment]
> The original issue requests that the spinning wheel be like the Payment Sent and Payment Received confirmation buttons, not a progress bar.
> 
> The spinning wheel should be to the right of the button.
> 
> Please test that the UI is similar and then let me know this is ready for review.

Oh. I did not fully finish reading your comments before committing. I made it such that the screen becomes inactive (a transparent overlay which ensures nothing on that screen can be clicked until the activity ends and the wheel disappears). This is more in line with UI designs. But if you insist, I will put the spinning wheel to the right of the button.

**Comment by woodser** [comment]
Ah, no, this looks good :)

**Review by woodser — APPROVED** [review]

**Comment by woodser** [comment]
Please squash to one commit with a final commit message on one line.

**Comment by niyid** [comment]
> Please squash to one commit with a final commit message on one line.

I know I have done squashes before, but for some reason all my commits when selected do not allow squash. Do I have the right privileges?

**Comment by woodser** [comment]
Should simply be:

```
git reset --soft HEAD~4
git commit -m "your message"
git push --force
```

**Comment by woodser** [comment]
The commit message title should be fewer than 72 characters, please.

**Comment by woodser** [comment]
The commit message should be descriptive, not just "Resolves issue #853", so people can tell from reading the commit logs.

I gave the example "Withdraw tx runs in separate thread while displaying spinning wheel", but up to you.

**Comment by woodser** [comment]
Ping @niyid

**Comment by niyid** [comment]
> Ping @niyid

Do you still use Matrix/Element? I sent you a pm.

**Comment by woodser** [comment]
I see your PM from a few days ago and replied, but Matrix has been having problems.

Please feel free to DM your address for payout.

**Comment by niyid** [comment]
Still same:

43fLNsTYYbeYFSg1rqSb5mRfj7Cdq2ZLNAvWUiDguZA3Xuxkh9RWc2mggcGSnvs7cGAHvi7fEm1PicKAh6YQ6DWTQrQvns3

**Comment by woodser** [comment]
Thanks. Payment sent.

**Comment by niyid** [comment]
Received. Thanks.

**Pull request merged**
