### PR TITLE
Add PayPal, CashApp, and Venmo support to Haveno

### PR DESCRIPTION
**Pull request by preland**
This PR addresses #948 and #685 by adding PayPal and CashApp as payment methods to Haveno. Venmo is also added, as it had some pre-existing code alongside CashApp from Bisq.

### CODE REVIEW

**Comment by woodser** [comment]
Please also register the form IDs in [PaymentAccountForm.java](https://github.com/haveno-dex/haveno/blob/879ed9b10a13e14ae2272e734ab6591eb6148c14/core/src/main/java/haveno/core/api/model/PaymentAccountForm.java#L61) and ensure the test `"Can validate payment account forms"` passes in [HavenoClient.test.ts](https://github.com/haveno-dex/haveno-ts/blob/dbd6b0e738ce442529faa0564ca8da6c1ee6ea4e/src/HavenoClient.test.ts#L1246), so they're fully integrated with the API.

Additionally, the payment methods need a warning popup about their high chargeback risk, shown when the payment account is created.

**Comment by preland** [comment]
On it; it should already be showing the chargeback risk screen when creating an account

**Comment by woodser** [comment]
FYI, Australia PayID was integrated and tested with the API in these PRs, for reference:

https://github.com/haveno-dex/haveno/pull/994
https://github.com/haveno-dex/haveno-ts/pull/288

**Comment by woodser** [comment]
I'd like to get this wrapped up for next release. I'm planning to work on it today, so might open a PR on your branch for inclusion.

**Comment by woodser** [comment]
Superseded by https://github.com/haveno-dex/haveno/pull/1007

**Pull request closed without merging**
