### PR TITLE
support buying xmr without deposit or fee using passphrase

### PR DESCRIPTION
**Pull request by woodser**

### CODE REVIEW

**Comment by shortwavesurfer2009** [comment]
Are you planning to set a 0.11xmr cap on this so its only use is nocoiners?

**Comment by monerobull** [comment]
cap should be 0.5 XMR or a bit lower, maybe 0.25. 0.11 is already annoyingly low if you have no xmr and want to put for example $300 into it (because you need multiple trades to just get the minimum deposit amount).

**Comment by woodser** [comment]
Limit set to 0.5 XMR for no deposit offers with passphrase.

**Comment by shortwavesurfer2009** [comment]
Hey, the version that implements this will be a mandatory upgrade correct. It seems like it would be a change to the protocol and therefore require all clients to upgrade.

**Comment by woodser** [comment]
Yeah it's best to be a mandatory update, otherwise trades will fail if non updated clients try taking the new offer type.

**Comment by woodser** [comment]
Limit bumped to 1 XMR from this conversation: https://github.com/haveno-dex/haveno/issues/1464#issuecomment-2545298727

**Pull request merged**
