### PR TITLE
Create haveno-system-tor.sh

### PR DESCRIPTION
**Pull request by XMRZombie**
Makes haveno interacting with Tor without wrapping (debian only)
```
chmod +x haveno-system-tor.sh && ./haveno-system-tor.sh
```

### CODE REVIEW

**Comment by woodser** [comment]
Thinking this would be better named `run-haveno-system-tor.sh` to be more clear that it's running Tor?

**Comment by XMRZombie** [comment]
Yeah I think it's fine

**Comment by woodser** [comment]
Nice. Can you add the user-docs as a separate PR from adding [run-]haveno-system-tor.sh?

**Comment by XMRZombie** [comment]
I'

**Pull request closed without merging**
