### PR TITLE
Create error logfile

### PR DESCRIPTION
**Pull request by preland**
This PR addresses #1252.

### CODE REVIEW

**Comment by woodser** [comment]
Overall this is working great from my testing; `ERROR` and `WARN` messages are logged to a dedicated file, and the logs are capped and recycled.

The only thing left that I'd hope to do is capture error stack traces to the log file.

Currently `err.printStackTrace()` writes only the error message but not the full stack trace to the log, which is crucial for debugging.

Possible to get this captured as well? That will close out this issue.

**Comment by preland** [comment]
I was unable to reproduce the issue with it logging stack traces; I edited the filter so that it wouldn't potentially cut off lines past 15, so that might help.

How exactly were you testing the stack trace log? I probably just need to reproduce what you are doing to see what's going on

**Comment by woodser** [comment]
> How exactly were you testing the stack trace log?

I was just throwing an error during the trade initialization protocol (in ProcessInitMultisigRequest.java iirc).

**Comment by preland** [comment]
> > How exactly were you testing the stack trace log?
> 
> I was just throwing an error during the trade initialization protocol (in ProcessInitMultisigRequest.java iirc).

And you get no stack trace when doing this (as opposed to it being truncated)?

**Comment by woodser** [comment]
I only saw the error message, but not the full trace.

**Comment by woodser** [comment]
Agreed changing current `printStackTrace` calls is beyond the scope of this PR, so we should open another issue to change those over.

**Comment by woodser** [comment]
Thanks for your contribution, please respond or DM with an address for payment. :)

**Comment by preland** [comment]
> Thanks for your contribution, please respond or DM with an address for payment. :)

You are welcome :) 

My address is 48pre1andu3Z8E186es2mZYBcHMTyowcn1DQ3htN6rLCGwG39ycDCeP8kSa3b7rqaZ6to3L1K7bd92fERMex3nEpJashdga

**Comment by preland** [comment]
Payment received:)

**Pull request merged**
