### PR TITLE
Add an additional "details" text area for PayPal

### PR DESCRIPTION
**Pull request by wp07e**
#1021 

This is only for Paypal accounts only. Probably need to do it for CashApp accounts as well.

Tested and verified on 1.0.7

### CODE REVIEW

**Comment by woodser** [comment]
For this and https://github.com/haveno-dex/haveno/pull/1035, please copy as done for PayByMail or CashAtAtm.

- The field in pb.proto is called `extra_info`.
- Add `PaymentAccountFormField.FieldId.EXTRA_INFO` to `INPUT_FIELD_IDS`.
- Uses `payment.shared.optionalExtra` translation.
- Ensure the test `Can validate payment account forms` passes in [HavenoClient.test.ts](https://github.com/haveno-dex/haveno-ts/blob/e348b2ec54e1fcc39e0b5cf105fcacf3ecf2f18e/src/HavenoClient.test.ts#L1246) by running the [API tests](https://github.com/haveno-dex/haveno-ts?tab=readme-ov-file#run-tests).

**Comment by woodser** [comment]
You can see all changes made to support extra info added to Australia PayID: https://github.com/haveno-dex/haveno/pull/994/files.

These PRs should include the same changes for extra info.

**Comment by wp07e** [comment]
Thanks for the tips I'll start looking at it

**Comment by wp07e** [comment]
I've tried running a basic test to get the version and I am getting this error:

`
 FAIL  src/HavenoClient.test.ts (18.228 s)
  ✕ Can get the version (CI) (2 ms)
  ○ skipped Can convert between XMR and atomic units (CI)
  ○ skipped Can manage an account (CI)
  ○ skipped Can manage Monero daemon connections (CI)
  ○ skipped Can start and stop a local Monero node (CI)
  ○ skipped Has a Monero wallet (CI)
  ○ skipped Can get balances (CI, sanity check)
  ○ skipped Can send and receive push notifications (CI, sanity check)
  ○ skipped Can get asset codes with prices and their payment methods (CI, sanity check)
  ○ skipped Can get market prices (CI, sanity check)
  ○ skipped Can get market depth (CI, sanity check)
  ○ skipped Can register as an arbitrator (CI)
  ○ skipped Can get offers (CI)
  ○ skipped Can get my offers (CI)
  ○ skipped Can get payment methods (CI)
  ○ skipped Can get payment accounts (CI)
  ○ skipped Can validate payment account forms (CI, sanity check)
  ○ skipped Can create fiat payment accounts (CI)
  ○ skipped Can create crypto payment accounts (CI)
  ○ skipped Can prepare for trading (CI)
  ○ skipped Can post and remove an offer (CI, sanity check)
  ○ skipped Can schedule offers with locked funds (CI)
  ○ skipped Can reserve exact amount needed for offer (CI)
  ○ skipped Cannot post offer exceeding trade limit (CI, sanity check)
  ○ skipped Can complete a trade within a range
  ○ skipped Can complete trades at the same time (CI, sanity check)
  ○ skipped Can complete all trade combinations (stress)
  ○ skipped Can go offline while completing a trade (CI, sanity check)
  ○ skipped Can resolve a dispute (CI)
  ○ skipped Can resolve disputes (CI)
  ○ skipped Can go offline while resolving a dispute (CI)
  ○ skipped Cannot make or take offer with insufficient unlocked funds (CI, sanity check)
  ○ skipped Invalidates offers when reserved funds are spent (CI)
  ○ skipped Can handle unexpected errors during trade initialization
  ○ skipped Selects arbitrators which are online, registered, and least used

  ● Can get the version (CI)

    Error: Http response at 400 or 500 level, http status code: 503
`

Do you know why? I will admit since I started working on Haveno I have caused conditions to create exceptions due to failed trades, "hash of peer's payment account payload does not match contract" exceptions, and various other exceptions but I don't believe those should effect the test correct? If necessary I can start with a clean version of haveno but this error seems unrelated.

**Comment by woodser** [comment]
Are you running the envoy proxy and funding wallet, from the instructions?

**Comment by wp07e** [comment]
Yes. I ran the envoy proxy. Here is a snippet of the output:
`
[2024-06-26 09:11:43.767][1][warning][misc] [source/common/protobuf/message_validator_impl.cc:21] Deprecated field: type envoy.config.route.v3.VirtualHost Using deprecated option 'envoy.config.route.v3.VirtualHost.cors' from file route_components.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.
[2024-06-26 09:11:43.768][1][warning][misc] [source/common/protobuf/message_validator_impl.cc:21] Deprecated field: type envoy.config.route.v3.VirtualHost Using deprecated option 'envoy.config.route.v3.VirtualHost.cors' from file route_components.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.
[2024-06-26 09:11:43.768][1][warning][misc] [source/common/protobuf/message_validator_impl.cc:21] Deprecated field: type envoy.config.route.v3.VirtualHost Using deprecated option 'envoy.config.route.v3.VirtualHost.cors' from file route_components.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.
[2024-06-26 09:11:43.768][1][warning][misc] [source/common/protobuf/message_validator_impl.cc:21] Deprecated field: type envoy.config.route.v3.VirtualHost Using deprecated option 'envoy.config.route.v3.VirtualHost.cors' from file route_components.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.
[2024-06-26 09:11:43.769][1][info][config] [source/server/configuration_impl.cc:154] loading stats configuration
[2024-06-26 09:11:43.769][1][warning][main] [source/server/server.cc:935] There is no configured limit to the number of allowed active downstream connections. Configure a limit in `envoy.resource_monitors.downstream_connections` resource monitor.
[2024-06-26 09:11:43.769][1][info][main] [source/server/server.cc:977] starting main dispatch loop
[2024-06-26 09:11:43.769][1][info][runtime] [source/common/runtime/runtime_impl.cc:625] RTDS has finished initialization
[2024-06-26 09:11:43.769][1][info][upstream] [source/common/upstream/cluster_manager_impl.cc:240] cm init: all clusters initialized
[2024-06-26 09:11:43.769][1][info][main] [source/server/server.cc:957] all clusters initialized. initializing init manager
[2024-06-26 09:11:43.769][1][info][config] [source/common/listener_manager/listener_manager_impl.cc:930] all dependencies initialized. starting workers
`
So you can see at the end, it mentions "starting workers" so I assume it is working correctly.

When I run the script to fund the wallet, this is the output:

`
user@localhost:~/temp/github/haveno$ make funding-wallet-local
./.localnet/monero-wallet-rpc \
	--testnet \
	--daemon-address http://localhost:28081 \
	--rpc-bind-port 28084 \
	--rpc-login rpc_user:abc123 \
	--rpc-access-control-origins http://localhost:8080 \
	--wallet-dir ./.localnet \

This is the RPC monero wallet. It needs to connect to a monero
daemon to work correctly.

Monero 'Fluorine Fermi' (v0.18.3.3-a04a280cc)
Logging to ./.localnet/monero-wallet-rpc.log
2024-06-26 09:11:50.368	I Binding on 127.0.0.1 (IPv4):28084
2024-06-26 09:11:51.421	W Starting wallet RPC server
2024-06-26 09:12:02.938	W Loaded wallet keys file, with public address: 9xSyMy1r9h3BVjMrF3CTqQCQy36yCfkpn7uVfMyTUbez3hhumqBUqGUNNALjcd7f1HJBRdeH82bCC3veFHW7z3xm28gug4d
`

I have both 'monerod1-local' and 'monerod2-local' running as well. 

But, yeah I pretty sure I followed all of the instructions to the tee.

**Comment by wp07e** [comment]
I will try with a new fresh copy

**Comment by wp07e** [comment]
Couple of questions:
1. From [https://github.com/haveno-dex/haveno/blob/master/docs/installing.md](https://github.com/haveno-dex/haveno/blob/master/docs/installing.md), after I shutdown "User1", "User2", and the "Arbitrator", I should still keep the "Seed" node and "monerod1-local", "monerod2-local" running right?
2. After I run envoy, the last few lines of output I get are
`
[2024-06-28 06:54:11.019][1][info][main] [source/server/server.cc:977] starting main dispatch loop
[2024-06-28 06:54:11.033][1][info][runtime] [source/common/runtime/runtime_impl.cc:625] RTDS has finished initialization
[2024-06-28 06:54:11.033][1][info][upstream] [source/common/upstream/cluster_manager_impl.cc:240] cm init: all clusters initialized
[2024-06-28 06:54:11.033][1][info][main] [source/server/server.cc:957] all clusters initialized. initializing init manager
[2024-06-28 06:54:11.033][1][info][config] [source/common/listener_manager/listener_manager_impl.cc:930] all dependencies initialized. starting workers
`
That looks correct right?
3. After I run 'make funding-wallet-local', I should see output like this:
`
2024-06-28 06:58:11.922	W Duplicate prefix in EnglishOld word list: reve
2024-06-28 06:58:11.922	W Duplicate prefix in EnglishOld word list: scra
2024-06-28 06:58:11.922	W Duplicate prefix in EnglishOld word list: spir
2024-06-28 06:58:11.922	W Duplicate prefix in EnglishOld word list: stra
2024-06-28 06:58:11.922	W Duplicate prefix in EnglishOld word list: thro
`

Ultimately, whether I have the monero daemons running or not, I seem go keep getting these failed to bind to port errors:
`
java.io.UncheckedIOException: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:10004
	at haveno.daemon.grpc.GrpcServer.start(GrpcServer.java:83)
	at haveno.daemon.app.HavenoDaemonMain.loginAccount(HavenoDaemonMain.java:172)
	at haveno.core.app.HavenoExecutable.onApplicationLaunched(HavenoExecutable.java:189)
	at haveno.core.app.HavenoHeadlessAppMain.onApplicationLaunched(HavenoHeadlessAppMain.java:76)
	at haveno.daemon.app.HavenoDaemonMain.onApplicationLaunched(HavenoDaemonMain.java:93)
	at haveno.common.UserThread.lambda$execute$0(UserThread.java:64)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at haveno.common.UserThread.execute(UserThread.java:61)
	at haveno.daemon.app.HavenoDaemonMain.launchApplication(HavenoDaemonMain.java:88)
	at haveno.core.app.HavenoExecutable.doExecute(HavenoExecutable.java:146)
	at haveno.core.app.HavenoHeadlessAppMain.doExecute(HavenoHeadlessAppMain.java:49)
	at haveno.core.app.HavenoExecutable.execute(HavenoExecutable.java:132)
	at haveno.daemon.app.HavenoDaemonMain.main(HavenoDaemonMain.java:52)
Caused by: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:10004
	at io.grpc.netty.shaded.io.grpc.netty.NettyServer.start(NettyServer.java:328)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:183)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:92)
	at haveno.daemon.grpc.GrpcServer.start(GrpcServer.java:80)
	... 12 more
Caused by: io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
Jun-28 03:00:19.549 [HavenoDaemonMain] ERROR h.core.app.HavenoHeadlessApp: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:10004 
`
And that seems to be triggering the `Error: Http response at 400 or 500 level, http status code: 503` errors. 

I ran `protoc` and it is running correctly and when I run `protoc-gen-grpc-web` it just hangs but seems to be installed correctly. Can you give me some insights on what I might be doing wrong?

**Comment by woodser** [comment]
To run the test, you'll need to have running:

- monerod1-local
- monerod2-local
- funding-wallet-local
- seednode-local
- envoy proxy

Also first quit any running instances of java, monerod, monero-wallet-rpc, in case an old process is interfering. If everything's running correctly and nothing is interfering, the tests ought to be able to run.

Someone else has reported they had to change instances of `host.docker.internal` to `0.0.0.0`, in case that helps.

**Comment by wp07e** [comment]
So the first point I have to make is I won't be able to work on this too much for another week or two so should I close these pull requests in the mean time?

My second question is I am beginning to think this might have something to do with Envoy but I am not sure. After I execute `sudo docker run --rm --add-host host.docker.internal:host-gateway -it -v ~/temp/github/tests/haveno-ts/config/envoy.test.yaml:/envoy.test.yaml -p 8079:8079 -p 8080:8080 -p 8081:8081 -p 8082:8082 -p 8083:8083 -p 8084:8084 -p 8085:8085 -p 8086:8086 envoyproxy/envoy-dev:latest -c /envoy.test.yaml` (notice I am using 'sudo' not sure if that matters), if I try to do something like `curl localhost:8081`, I get **"upstream connect error or disconnect/reset before headers. reset reason: connection timeout"**. Can you check to see if that is the same behavior you are seeing?

**Comment by wp07e** [comment]
I figured it out. It was envoy. You need to add `--network host` flag to `docker run` command as stated here https://stackoverflow.com/questions/69897433/envoy-upstream-connect-error-or-disconnect-reset-before-headers-reset-reason. So that answers one question but I still won't be able to work on this very much for the next week or so so if you want to tackle it or have someone else tackle it I will close this and the other related pull request. Just let me know

**Comment by woodser** [comment]
Thanks, I added the `--network host` flag: https://github.com/haveno-dex/haveno-ts/pull/293

**Comment by wp07e** [comment]
Hey I can prob. start working on this this weekend. Two questions: 

1. Are you planning on working on this so we don't duplicate the work?
2. When is the next release planned for?

Thanks

**Pull request closed without merging**
