### PR TITLE
Allow user to set public keys via text file in appdata dir instead of modifying source code

### PR DESCRIPTION
**Pull request by mcneb10**
Self explanatory, should be much easier to deploy

I'm also not entirely clear on what all the public keys do exactly except the arbitrator one, so I decided to move all of them to their own files

### CODE REVIEW

**Comment by mcneb10** [comment]
should have tried compiling it first lmao, will try to fix

**Comment by chefnaphtha** [comment]
consider #911, explains what exactly needs to be changed too. changing the arbitrator keys isnt enough to switch networks

**Comment by mcneb10** [comment]
> consider #911, explains what exactly needs to be changed too. changing the arbitrator keys isnt enough to switch networks

I like your idea of a single json file better. I'll change my code to use that instead

**Comment by chefnaphtha** [comment]
nice, though i don't think having different public keys per file (`alertKeys`, `arbitratorKeys`, `filterKeys` and `privateNotificationKeys`) is a good idea, i'm not even sure if haveno will work if those keys are different(?) @woodser

**Comment by chefnaphtha** [comment]
it would also be nice to have a "network name" key in the json file for the application folder name, using different networks with the same application folder will not work.

according to https://github.com/haveno-dex/haveno/commit/e30a247898ffff874d03eec9b3c0450589c00e16?short_path=c42a7e1#diff-c42a7e141bc09b07e06393cac408f728065a0caea369cfa9fea268eede4e7c22 `DEFAULT_APP_NAME` in `HavenoExecutable.java` needs to use that network name, as well as any code that gets the `appName` argument when running the different executables

**Comment by mcneb10** [comment]
Should the code throw an exception if it can't find keys? It does this right now and causes a bunch of tests to fail. I changed the code so it touches the JSON file in Mainnet mode but that doesn't seemed to have helped much

**Comment by chefnaphtha** [comment]
i think it should just use the default testnet network by default, i'm not a haveno dev so i can't exactly say if it should or shouldnt throw but common sense says that haveno should preferably never crash. in the future an ui popup would be nice, informing the user that they're on the official haveno testnet, not a production mainnet haveno network

**Comment by mcneb10** [comment]
Really sorry about this, but I made this pull request at the worst possible time for myself. I will continue be unavailable for development until the middle of next week with perhaps an opening during the weekend. If anyone wants to help make this PR actually do what it’s supposed to go ahead

**Pull request closed without merging**
