### PR TITLE
Allow for word wrapping on "Accepted taker countries" field

### PR DESCRIPTION
**Pull request by wp07e**
#989

Tested and Verified on 1.0.7

(I had to start over with a different clone)

### CODE REVIEW

**Comment by walkerp07** [comment]
Its been awhile since I have used github but I was expecting only the last commit to be on this branch and to not have all of my other commits. Do you know what that happened because I used a new branch for this commit

**Comment by woodser** [comment]
Yeah the other commits will need to be removed.

Should be as easy as:

```
git checkout 989_list_cutoff
git reset --hard master
git cherry-pick 06ec2dae12d8e9de7b2a45cdb499e32dd92702a7
git push --force 989_list_cutoff
```

**Comment by woodser** [comment]
Minor nit, but do you mind pushing the "Accepted taker countries" label up so it's top-justified with the country values, instead of middle-justified:

image

**Comment by wp07e** [comment]
Just to be clear, instead of:

My Trading                                   SEPA (...
Accepted taker countries          AD, AT, BE...

You want:

My Trading                                   SEPA (...
                                                       Accepted taker countries
                                                       AD, AT, BE...


That does not seem right but not sure

**Comment by wp07e** [comment]
Ok, here you go:

image

**Pull request merged**
