### PR TITLE
Updated build instructions with missing Arch Linux section

### PR DESCRIPTION
**Pull request by Ysujy**
Added missing dependency section for Arch Linux. Previously, the doc listed the Arch Linux instructions under Windows.

### CODE REVIEW

**Comment by woodser** [comment]
Pacman is used on Windows too, so it should remain under the Windows section. The new section for Arch Linux looks good though, so this PR just needs that one change.

**Review by woodser — CHANGES_REQUESTED** [review]
Pacman is used on Windows too, so it should remain under the Windows section. The new section for Arch Linux looks good though, so this PR just needs that one change.

**Comment by woodser** [comment]
Ping @Ysujy

**Comment by notsungod** [comment]
There are no such packages to install with pacman: `mingw-w64-x86_64-toolchain, mingw-w64-x86_64-cmake` .

**Pull request closed without merging**
