### PR TITLE
#967 Text in Pop Ups selectable

### PR DESCRIPTION
**Pull request by nsec1**
#967

### CODE REVIEW

**Comment by woodser** [comment]
This change does make the text selectable in most popups, but also introduces a subtle shaded line in every popup, which takes away from UI cleanliness:

image

image

image

Can this line be removed?

Additionally, text still cannot be selected in the alert message popup:

image

You can test sending a message alert with `ctrl + m` and unchecking the "Software download notification" checkbox.

This popup is handled in [DisplayAlertMessageWindow.java](https://github.com/haveno-dex/haveno/blob/master/desktop/src/main/java/haveno/desktop/main/overlays/windows/DisplayAlertMessageWindow.java).

**Comment by nsec1** [comment]
What is the key (Unlock)?
Screenshot from 2024-06-22 11-30-30

**Comment by woodser** [comment]
It's filled in automatically on the test network, or you can use `9487981d751e9c04e41a3e3d08e17b2a2fc21d59a94dcca38d90fae2bef2c9fc` on stagenet.

**Comment by nsec1** [comment]
Still working on alert

**Pull request merged**
