### PR TITLE
Fixed sorting on Buy>XMR

### PR DESCRIPTION
**Pull request by niyid**
Fixes issue #1088

### CODE REVIEW

**Comment by woodser** [comment]
This PR does not fix the problem when the offer book is showing all currencies. The sorting does not work in the `Amount` column.

image

**Comment by niyid** [comment]
> This PR does not fix the problem when the offer book is showing all currencies. The sorting does not work in the `Amount` column.
> 
> image

Apologies for my confusion. I see the amounts sorted in ascending order.

**Comment by woodser** [comment]
>  I see the amounts sorted in ascending order.

The issue is that the column does not re-sort by clicking the column header `Amount (min - max)`.

**Comment by niyid** [comment]
> > I see the amounts sorted in ascending order.
> 
> The issue is that the column does not re-sort by clicking the column header `Amount (min - max)`.

There may be some mistake here. My screenshots are below for both Buy and Sell offers:

BUY
Screenshot from 2024-10-30 01-17-40

Screenshot from 2024-10-30 01-18-18

SELL
Screenshot from 2024-10-30 01-54-03

Screenshot from 2024-10-30 01-54-55

**Comment by woodser** [comment]
The arrow to indicate it's sorting, ▲, should be to the right of the `Amount (min-max)` column header.

The arrow you're showing is for sorting the `XMR (min-max)` column header, not `Amount (min-max)`.

When you click on `Amount (min-max)` column header, you should observe that that column is not sorting.

**Pull request closed without merging**
