### PR TITLE
fix color scheme of offer book in market view

### PR DESCRIPTION
**Pull request by DomPro11**
Fixed the white on white text color in the market view when light theme is enabled by adding definitions to theme-light.css

### CODE REVIEW

**Review by erciccione — APPROVED** [review]
Tested ACK

Thanks @DomPro11!

**Review by erciccione — CHANGES_REQUESTED** [review]
Actually i just hit a bug where clicking the "Market" doesn't work and the terminal throws a warning:

```
WARNING: Caught 'java.lang.ClassCastException' while converting value for '-fx-text-fill' from rule '*.label' in stylesheet jar:file:/home/calcifer/DEV/haveno/haveno-dex/haveno/lib/javafx-controls-15-linux.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Sep 21, 2022 11:27:50 AM javafx.scene.CssStyleHelper calculateValue
```

I couldn't find the trigger, but once it happens it's impossible to navigate to the "Market" page.

**Comment by erciccione** [comment]
I keep hitting that bug where, i cannot click on the "market" tab after i left it. I deleted local files and done a clean build. Not sure what the problem is. The warning is not there anymore tough.

**Comment by DomPro11** [comment]
I discovered more details about the bug, but since it is present in the current master branch I think it should be addressed as a separate issue (which I would be happy to work on). I'm able to reliably reproduce it after cloning and clean building the master branch by clicking on my own offer in the Market View. The UI will then take me to the Buy (or Sell) tab, and switching back to the Market tab will have the program immediately switch to the Buy/Sell tab again. 

Unconfirmed, but I think this has something to do with the `goToOfferView()` function defined in `desktop/src/main/java/bisq.desktop/main/market/offerbook/OfferBookChartViewModel.java` line 223. The BUY/SELL XMR buttons call this function and behave as expected (can still go back to Market View), but there's a `buyTableRowSelectionListener` in `desktop/src/main/java/bisq.desktop/main/market/offerbook/OfferBookChartView.java` which calls this function, and I don't think `deactivate()` is ever called which contains the `removeListener()` method. Again I haven't confirmed whether this is related to the cause, these are just my thoughts briefly after discovering the bug.

**Comment by woodser** [comment]
Now getting a build error with `make clean && make`:

```
> Task :assets:test
java.lang.instrument.IllegalClassFormatException: Error while instrumenting sun/util/resources/cldr/provider/CLDRLocaleDataMetaInfo.
        at org.jacoco.agent.rt.internal_3570298.CoverageTransformer.transform(CoverageTransformer.java:94)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
        at java.base/java.lang.ClassLoader.defineClass2(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1104)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:182)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:741)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClass(BuiltinClassLoader.java:621)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:633)
        at java.base/java.lang.Class.forName(Class.java:584)
        at java.base/java.lang.Class.forName(Class.java:559)
        at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:859)
        at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(ServiceLoader.java:1084)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
        at java.base/sun.util.cldr.CLDRLocaleProviderAdapter.lambda$new$0(CLDRLocaleProviderAdapter.java:84)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at java.base/sun.util.cldr.CLDRLocaleProviderAdapter.<init>(CLDRLocaleProviderAdapter.java:83)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
        at java.base/sun.util.locale.provider.LocaleProviderAdapter.forType(LocaleProviderAdapter.java:189)
        at java.base/sun.util.locale.provider.LocaleProviderAdapter.findAdapter(LocaleProviderAdapter.java:288)
        at java.base/sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:259)
        at java.base/java.util.Calendar.createCalendar(Calendar.java:1688)
        at java.base/java.util.Calendar.getInstance(Calendar.java:1656)
        at java.base/java.text.SimpleDateFormat.initializeCalendar(SimpleDateFormat.java:680)
        at java.base/java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:624)
        at java.base/java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:603)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.getLastResortErrorLogFile(SystemApplicationClassLoaderWorker.java:162)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:111)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.io.IOException: Error while instrumenting sun/util/resources/cldr/provider/CLDRLocaleDataMetaInfo.
        at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrumentError(Instrumenter.java:160)
        at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrument(Instrumenter.java:110)
        at org.jacoco.agent.rt.internal_3570298.CoverageTransformer.transform(CoverageTransformer.java:92)
```

**Review by erciccione — APPROVED** [review]
Thanks @DomPro11 and thanks for looking the issue up! I opened #449 to keep track of the bug, this PR can move on in the meantime IMO :)

**Pull request merged**
