### PR TITLE
chore: split binary artifacts

### PR DESCRIPTION
**Pull request by Jabster28**
This keeps the version string for now.

### CODE REVIEW

**Comment by woodser** [comment]
I'm hesitant to extract the installers from the zip file automatically.

Currently the zip files contain `desktop-1.0.11-SNAPSHOT-all.jar.SHA-256` for verification.

But, maybe it's not actually helpful to keep this file?

**Comment by Jabster28** [comment]
@woodser I think it could still be useful. If a binary doesn't pass `gpg` verification but does match the signature, it's highly likely that the wrong key is being used and can be reported upstream as an issue quicker.
We could do [what feather wallet does](https://github.com/feather-wallet/feather/releases) and hash the files individually, also putting them in release notes:

image

**Comment by woodser** [comment]
Ok, then for this PR, I think we should only split the distributions into different zips, but preserve the zip contents.

**Comment by boldsuck** [comment]
> We could do [what feather wallet does](https://github.com/feather-wallet/feather/releases) and hash the files individually, also putting them in release notes:

Oh, that would be nice. Haveno can then be verified with a one-liner like Feather and Monero.
_reto *-hashes.txt is meh_

**Comment by woodser** [comment]
This is the latest output from this PR:

image

Thinking about this further, I'm thinking we should take Feather Wallet's approach, and output 4 zips with exactly these names:

- haveno-1.0.11-mac.zip
- haveno-1.0.11-windows.zip
- haveno-1.0.11-linux-deb.zip
- haveno-1.0.11-linux-rpm.zip

Additionally, I think the installers within the zips should **exclude** the version number, with exactly these names:

- Haveno.dmg
- Haveno.deb
- Haveno.rpm
- Haveno.exe

Or alternatively, include the architecture, with exactly these names:

- Haveno-x86_64.dmg
- Haveno-x86_64.deb
- Haveno-x86_64.rpm
- Haveno.exe (exclude for Windows)

For consistency, every zip should extract to a folder with the `desktop-1.0.X-SNAPSHOT-all.jar.SHA-256` file, or extract directly to the binary installer, but I think all should be consistent.

We should aim to be precise and consistent for processing with scripts.

What do you guys think?

**Comment by Jabster28** [comment]
@woodser That sounds fine. Just a note for anyone here or planning on editing GH actions - as far as i know, the artifacts are zipped when you download them through the website, regardless of what you upload.

I think including architecture would be a good idea if we're planning on adding ARM support. Is there a reason we're excluding the arch on windows? macOS has support for builds with multiple architectures as far as I know.

**Comment by Jabster28** [comment]
Now that I think about it, I've seen some GH projects upload files without zipping them. Perhaps that's possible with newer versions of the artifact uploader? I'll look into it this afternoon.

**Comment by woodser** [comment]
> Is there a reason we're excluding the arch on windows

My understanding is it's generally acceptable to exclude the architecture for Windows which is almost always x86_64 (true in our case).

**Comment by woodser** [comment]
>  I've seen some GH projects let you download files without zipping them

In our case we will be downloading zips, though, according to the above.

**Comment by Jabster28** [comment]
>  is almost always x86_64

Will this be true in the future? Windows seems to be moving towards ARM processors, though who knows if that'll continue.

**Comment by woodser** [comment]
Ok in that case let's include the architecture on that too :)

**Comment by woodser** [comment]
It's looking good. The only thing I'm thinking is it's worth preserving the `desktop-1.0.11-SNAPSHOT-all.jar.SHA-256` file alongside the binary installer, for extra security. So these zips should each extract to a folder which contains the binary installer and the `desktop-1.0.11-SNAPSHOT-all.jar.SHA-256` file. This preserves how the zip content works now.

**Comment by woodser** [comment]
Another thing I noticed in addition to the SHA-256 files missing from the zip, is that the name of the extracted folder should match the name of the zip, as it is currently (I'm seeing the folder name "release" in the latest commit).

**Comment by woodser** [comment]
Hey just checking in. Hoping we can finish this soon since we're close. :)

**Comment by Jabster28** [comment]
Forgot to commit that :sweat_smile:

**Comment by woodser** [comment]
The zip files are still being extracted to a folder named "release", whereas it should match the name of the zip file, as done on master, to avoid conflicts.

**Comment by woodser** [comment]
Hey @Jabster28, checking in. Once this PR is finalized, I can start testing the app image and flatpak prs with the new naming scheme.

**Comment by Jabster28** [comment]
@woodser Strange, the CI is now erroring with
> OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Failed to map supported failure 'org.opentest4j.AssertionFailedError' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@22955ef2': Cannot invoke "Object.getClass()" because "obj" is null
Failed to map supported failure 'org.opentest4j.AssertionFailedError' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@22955ef2': Cannot invoke "Object.getClass()" because "obj" is null

since my commit, but I haven't changed gradle. Maybe `ubuntu-latest` upgraded something? Those should probably be pinned.

**Comment by woodser** [comment]
Only mac and windows are created with the last update:

image

**Comment by woodser** [comment]
@Jabster28 I'd like to be closing this out so I can test the flatpak and AppImage prs built on the new naming convention.

**Comment by woodser** [comment]
Sorry for the changes. We can increase the bounty further if needed.

**Comment by woodser** [comment]
I think this updates to all the changes we want, and rebases on master to resolve the merge conflict: https://github.com/haveno-dex/haveno/pull/1301

It still uploads to .zip files instead of tar.gz which appears to be a limitation of the github workflow: https://github.com/actions/upload-artifact/issues/109

In this case #1301 supersedes this PR.

**Comment by woodser** [comment]
Superseded by https://github.com/haveno-dex/haveno/pull/1301

**Pull request closed without merging**
