### PR TITLE
dockerfiles and docker-compose.yml for running test network

### LINKED ISSUE #284: Dockerize deamons
This is needed to make the life of the UI team simpler.

We need to run on Docker:

- seednode
- arbitrator-daemon
- alice-daemon
- bob-daemon
- Monero

It will also help for #21

### PR DESCRIPTION
**Pull request by erciccione**
Closes #284

~~Posting as draft because~~ we have to make sure we introduce all functionalities required by @haveno-dex/frontend and that everything works as expected.

### CODE REVIEW

**Comment by abouolia** [comment]
@erciccione Tried to run the docker compose containers and everything worked well, but when trying to run the test cases of haveno-ts, all tests fail because the arbitrator doesn't run. how can we solve that issue?

**Comment by CryptoGrampy** [comment]
Nice work on this @erciccione :)

**Comment by erciccione** [comment]
@abouolia i just added `arbitrator-daemon` to the compose file with the last commit. Let me know if that resolves the issue.

@CryptoGrampy thanks :)

I'm having some problems reaching the pricenode with the local instances, but i seem to be able to curl the feed just fine. Please let me know if you are also seeing this issue.

**Comment by abouolia** [comment]
@erciccione  "--nodePort=4444" NOT  --"nodePort=4444" in docker-compose file arbitrator-daemon line.

**Comment by erciccione** [comment]
@abouolia 

> would be better if that pushed the docker images to the public registry, building these images on local machines takes a lot of resources and time

Yes, once we have a stable and working image, we plan to add it to docker hub :)

> "--nodePort=4444" NOT --"nodePort=4444" in docker-compose file arbitrator-daemon line.

Thanks, will fix

>  except the arbitrator-daemon keep getting

Will look into it. Note that when i started to work on the docker images, arbitrator-daemon didn't exist. So in the meantime, you should be able to run arbitrator-desktop (and register the arbitrator) in the UI for running the tests.

**Comment by abouolia** [comment]
@erciccione Tried to run `arbitrator-desktop` but was unable to recognize the seednode. keep getting `There's no seed nodes` error.

**Comment by erciccione** [comment]
My laptop recnetly broke and i'm waiting for a new one. I'll resume work on this as soon as i can.

**Pull request closed without merging**
