### PR TITLE
Set selected color of radio buttons to Haveno blue

### PR DESCRIPTION
**Pull request by coinstudent2048**
Resolves: #634

### CODE REVIEW

**Review by woodser — APPROVED** [review]
Nicely done!

**Comment by woodser** [comment]
@coinstudent2048 I can merge this to be included in the next release once you mark as ready for review instead of draft.

**Comment by coinstudent2048** [comment]
@woodser Ok I set this to review, but

I am also considering the checkbox, which is also green. Do you want that to be blue too? I also made the checkboxes such that when ticked, the inside is blue, but I am not satisfied because the border line of square is still green for some reason. This is the reason for the draft.

**Comment by woodser** [comment]
Hm gotcha, yeah ideally the checkboxes would be blue too, if it's possible to find the customization.

**Comment by coinstudent2048** [comment]
Hello. Radio buttons and check boxes are now set to Haveno blue.

**Comment by woodser** [comment]
Looks good. Thanks!

**Pull request merged**
