### PR TITLE
Unselect payment method currencies by default #1021

### PR DESCRIPTION
**Pull request by wp07e**
#1021

This fixes the issue where all of the currencies are checked by default.
Compiled and verified on 1.0.7

Do we really want add in an additional area to enter trade details like OP is requesting?

### CODE REVIEW

**Comment by woodser** [comment]
Thanks. We can handle the addition of the details text area in a separate PR.

**Comment by walkerp07** [comment]
Hey I made a mistake. I think my change effect all payment types not just Paypal. Is that OK or does this need to be specific to Paypal?

**Comment by walkerp07** [comment]
Give me a min I will update it so only paypal currencies are not checked

**Comment by walkerp07** [comment]
On second thought I think it makes sense to leave all currencies unchecked by default

**Comment by walkerp07** [comment]
I will work on adding 

> Thanks. We can handle the addition of the details text area in a separate PR.

Ok sounds good

**Comment by woodser** [comment]
There's a bug with this PR where selected trade currencies become unselected when reviewing the payment account.

For example, first create a PayPal account which accepts USD.

After creating the account, select the PayPal account, and USD is unselected:

image

**Comment by wp07e** [comment]
Opps didn't realize that I will take another look at it

**Pull request closed without merging**
