### PR TITLE
fix: use pre-built app-image for build process

### LINKED ISSUE #1280: Build app as a JPackage app-image before making other installers [1 XMR]
Right now, the Linux CI builder uses JPackage to build for each platform, but the package is reset every time. JPackage supports building into an intermediary app-image (not an [AppImage](https://appimage.org/)) and building the individual installers on top of that. Using this instead of rebuilding that will save a lot of CI minutes, and may be necessary once we also have Flatpaks and AppImages.

I've been thinking of doing this for a bit, and @\TheTollingBell raised the idea of putting it in an issue. I'll try and get this done after we merge these two PRs, as that'll be less likely to break anything.

### PR DESCRIPTION
**Pull request by TheTollingBell**
This fixes #1280.

### CODE REVIEW

**Comment by TheTollingBell** [comment]
To be honest, the CI improvements weren't as big as I expected as there is still a large portion of time devoted to packaging from an app-image to each of the individual installers. If we wanted to significantly improve CI times a complete rewrite of the `package.gradle` file would probably be best, using much less `doLast` blocks and splitting the building of each installer into their own gradle task allowing for parallelization. It would also make adding new installers or selectively building installers much easier.

**Comment by TheTollingBell** [comment]
I'm running a check now to make sure that the installers built before my changes are exactly the same as after.

**Comment by woodser** [comment]
Given that building to intermediary app image does not improve CI time as hoped, at least without more significant refactoring, I'm wondering if this PR provides other tangible benefits worth merging, or if it's not worth worrying about.

**Comment by woodser** [comment]
Please provide an address for the effort which will be archived :)

**Comment by TheTollingBell** [comment]
```
45ZXas7gQJmUKHqJsxbP2mgupHRGcSRe5Z42QDcAXTFi3meXmGm7AaUSGhid8ZXb1m1Q74EZeHUBqVe4hSFD9vNsEt4fzdz
```

**Comment by woodser** [comment]
Thanks.

**Comment by TheTollingBell** [comment]
Thank you, XMR was recieved.

**Pull request closed without merging**
