### PR TITLE
Update Fango (XFG) asset information

### PR DESCRIPTION
**Pull request by aejontargaryen**
Renamed files & info from Dragonglass on old bisq version to current Fango information + new address validation

### CODE REVIEW

**Comment by erciccione** [comment]
I guess you are looking for bisq: https://github.com/bisq-network/bisq :)

**Comment by aejontargaryen** [comment]
No thanks. Fuck bisq.
I'm trying to update our info on Haveno.
Did  i miss something?

**Comment by erciccione** [comment]
Haveno is not live yet and most of the currencies listed will be removed. We will support only few currencies initially.

**Comment by aejontargaryen** [comment]
Inspiring. 
Thanks for the clarification.

**Pull request closed without merging**
