### PR TITLE
bisq.cli tools to haveno.cli tools

### PR DESCRIPTION
**Pull request by newsyp**
Progress Report.

Within the haveno/cli/src/main/java/bisq/cli I’ve commented out every line of code that had bisq and replaced them with new lines of code with bisq edited to haveno.

In order to edit out all the code from bisq to haveno in these files I went into haveno/proto/src/main/proto and within that directory I commented out any code containing bisq and edited the code to say haveno instead. 

I decided to comment out all previous code instead of deleting it, in the case that we run into issues in the future due to these changes. All of my changes sit at the top of the code for these files since I didn’t see bisq used anywhere passed the main method.

### CODE REVIEW

**Comment by premek** [comment]
- when renaming packages the java files should be moved to a directory according to the new package name
- i wouldn't leave the old code commented out, we have git history in case we need to go back
- this could be done in bulk for all the remaining files

**Comment by newsyp** [comment]
>     * when renaming packages the java files should be moved to a directory according to the new package name
> 
>     * i wouldn't leave the old code commented out, we have git history in case we need to go back
> 
>     * this could be done in bulk for all the remaining files


* I was trying to make a folder called haveno to move all these edited files into but the only option I found was one to create a file. You can see what I'm talking about at the end of my commits with the create haveno then delete haveno. How do I make a folder on here?

* Git history... still noob, where can I find that?

* I'm willing to do that. :)

**Comment by erciccione** [comment]
> Git history... still noob, where can I find that?

You can see an introduction to git here: https://www.freecodecamp.org/news/what-is-git-and-how-to-use-it-c341b049ae61/. Every group of changes (commit) is stored in the git history, so if we want we can revert/edit these commits. Delete the parts we don't need please, as @premek pointed out we can always revert a commit.

**Comment by woodser** [comment]
The PR needs to be resubmitted after resetting to the new rebased repo.

**Comment by newsyp** [comment]
Gotcha, will be putting further work into this pr as I finish whats left of my finals.

**Pull request closed without merging**
