### PR TITLE
Update Litecoin address validation to include non-legacy addresses.

### PR DESCRIPTION
**Pull request by OrginalS**
Related to https://github.com/haveno-dex/haveno/issues/787

Created regex based litecoin address validator.

Updated Litecoin.java to use new regex validator instead of old Base58 one.

Added new test cases.

I don't know Java and haven't tested it but LGTM.

### CODE REVIEW

**Comment by woodser** [comment]
It's failing on compile-time errors. Per the CI test failures:

```
/home/runner/work/haveno/haveno/assets/src/main/java/haveno/asset/LitecoinAddressValidator.java:26: error: illegal escape character
        super("^(?:(?:litecoin|Litecoin|LITECOIN):)?([LM3]{1}[a-km-zA-HJ-NP-Z1-9]{26,33}|ltc1[a-z0-9]{39,59})(?:\?time=\d+(?:&exp=\d+)?)?$");
                                                                                                                                   ^
/home/runner/work/haveno/haveno/assets/src/main/java/haveno/asset/LitecoinAddressValidator.java:30: error: illegal escape character
        super("^^(?:(?:litecoin|Litecoin|LITECOIN):)?([LM3]{1}[a-km-zA-HJ-NP-Z1-9]{26,33}|ltc1[a-z0-9]{39,59})(?:\?time=\d+(?:&exp=\d+)?)?$", errorMessageI18nKey);
                                                                                                                  ^
/home/runner/work/haveno/haveno/assets/src/main/java/haveno/asset/LitecoinAddressValidator.java:30: error: illegal escape character
        super("^^(?:(?:litecoin|Litecoin|LITECOIN):)?([LM3]{1}[a-km-zA-HJ-NP-Z1-9]{26,33}|ltc1[a-z0-9]{39,59})(?:\?time=\d+(?:&exp=\d+)?)?$", errorMessageI18nKey);
                                                                                                                         ^
/home/runner/work/haveno/haveno/assets/src/main/java/haveno/asset/LitecoinAddressValidator.java:30: error: illegal escape character
        super("^^(?:(?:litecoin|Litecoin|LITECOIN):)?([LM3]{1}[a-km-zA-HJ-NP-Z1-9]{26,33}|ltc1[a-z0-9]{39,59})(?:\?time=\d+(?:&exp=\d+)?)?$", errorMessageI18nKey);
``

**Comment by OrginalS** [comment]
How do you escape regex characters in Java?

**Comment by woodser** [comment]
AFAIK any backslashes need escaped so `\\` to represent `\` in regex.

**Comment by OrginalS** [comment]
Second one has an extra ^

**Comment by OrginalS** [comment]
Tests passed but I don't know if regex will match.

I think there was an issue with \d and it should be replaced with [0-9].
I don't know if \\? part will be correct, the desired result is escaping ?, won't \\? result in \ being escaped and ? being aplied to it as a regex token?

**Comment by OrginalS** [comment]
Should I remove the `(?:\?time=\d+(?:&exp=\d+)?)?` part?
It matches recive requests generated by electrum, I don't know if you guys want to allow thoes.

**Comment by woodser** [comment]
It should support only strictly valid address formats for payment destinations, without any other information about the payment or conventions used by apps.

**Comment by OrginalS** [comment]
I removed `(?:\?time=\d+(?:&exp=\d+)?)?` (electrum payment request format) but left `litecoin:` prefix as it's also allowed (but not tested for) for BitcoinCash.

**Comment by woodser** [comment]
I've opened a PR to validate Litecoin addresses based on Bisq's implementation using bitcoinj: https://github.com/haveno-dex/haveno/pull/815, and added you as a co-author for the address tests. This should provide a more robust validation than regex.

**Comment by OrginalS** [comment]
👍

**Pull request closed without merging**
