### PR TITLE
#919 Expand "Extra info" field on offers

### PR DESCRIPTION
**Pull request by nsec1**

### CODE REVIEW

**Comment by woodser** [comment]
We should apply a max height to cap long descriptions, which can be problematic on lower res screens:

image

**Comment by nsec1** [comment]
I used `prefHeightProperty`, it self adjusts to screen height

**Comment by woodser** [comment]
> I used prefHeightProperty, it self adjusts to screen height

I'm not seeing this behavior when I tested with lower resolution. It's cut off:

image

**Comment by nsec1** [comment]
> > I used prefHeightProperty, it self adjusts to screen height
> 
> I'm not seeing this behavior when I tested with lower resolution. It's cut off:

Which resolution is it?
I tested in gnome/debian with 1024x768 and 800x600 with no cut off. See the examples:

**Comment by woodser** [comment]
The problem is evident with any resolution on macOS, tested down to 1168x755.

Maybe rather than adjusting based on resolution or window height, the textarea height could be up to a maximum based on the length of the text.

**Comment by woodser** [comment]
Seems to work well. Thanks!

**Pull request merged**
