### PR TITLE
implement protocol v2

### PR DESCRIPTION
**Pull request by woodser**
This PR reaches parity with master using the new [trade protocol](https://github.com/haveno-dex/haveno/blob/master/docs/trade_protocol/trade-protocol.md):

- Outputs are reserved locally until used in a trade to avoid unecessary on-chain tx
- Trades complete after 10 confirmations by direct depositing to multisig
- Arbitrator signs "reserve tx" from maker and taker to secure trades
- Arbitrator broadcasts deposit txs so neither maker nor taker "go first"
- Sensitive payment account info is shared after funds are committed to multisig
- Uses monero-java 0.5.4 to freeze and thaw outputs

### CODE REVIEW

**Comment by erciccione** [comment]
Pinging @haveno-dex/developers

**Comment by woodser** [comment]
The 3 codacy checks are a result of open todos which are documented so we're ignoring them.

To test this PR:

1. `git clone https://github.com/haveno-dex/haveno.git`
2. `cd haveno`
3. `git pull origin pull/107/head`
4. delete existing application folders for the arbitrator, alice, and bob if haveno was previously launched
5. follow the usual instructions to launch a test network: https://github.com/haveno-dex/haveno/blob/master/docs/installing.md

**Review by erciccione — APPROVED** [review]
Tested it and everything went flawlessly :)

**Comment by HoverHalver** [comment]
Hello, 
I did follow the above recommendations in order to test.
Everything seems fine (I just had to install monero-wallet-rpc in my ~github/haveno directory).
I'm however stupidelly stucked at the end of step 5 from 
https://github.com/haveno-dex/haveno/blob/master/docs/installing.md

In monerod, I did 
start_mining ADDRESS 1, for Alice's address
stop_mining
start_mining ADDRESS 1, for Bob's address
stop_mining

But :
I don't see a "funds" tab in the haveno appli ?
(like in Bisq, in order to see the funds). Is this normal ?

https://github.com/haveno-dex/haveno/blob/master/docs/installing.md
says : Remember to send funds to both Alice and Bob.
... but how to do that ?
and I though that start_mining ADDRESS 1, for Alice's address would directly put the funds on this address.

Sorry but I have never mined before.

**Comment by woodser** [comment]
@HoverHalver There is no funds tab for the Monero wallet in this GUI. You should see your locked balance in the upper right increase with each block mined to the trader's address. Funds received from each mined block become available to spend after 60 blocks. Your available balance is shown next to "Balance" in the upper right.

**Comment by HoverHalver** [comment]
First remarks while testing.
Concerning the funds in the upper right :
1/ probably there are way too much digits used, which doesn't help at all imo. 
2/ for my Alice funds, there is ~2500 XMR available, and ~2000 XMR locked, and the Haveno appli is open for more than 10 hours. Is it normal to still have so much locked funds ? (For Bob's funds, 100% of funds are available).

**Comment by woodser** [comment]
> for my Alice funds, there is ~2500 XMR available, and ~2000 XMR locked, and the Haveno appli is open for more than 10 hours. Is it normal to still have so much locked funds

The funds should become unlocked after 60 blocks if from mining. If you mine new blocks to the address, you'll continue to have locked funds.

**Comment by HoverHalver** [comment]
> The funds should become unlocked after 60 blocks if from mining.
> If you mine new blocks to the address, you'll continue to have locked funds.

I mined for Alice's address for blocks 1681 to 2125
I mined for Bob's address for blocks 2126 to 2250
Now, Status tells : 2251/2251 100% on Stagenet,
So, this is more than 126 blocks after last block mined for Alice (2125).
It seems me that Alice should have all it's funds available (?)

**Comment by woodser** [comment]
Do the locked funds go to zero if you restart Alice?

**Comment by HoverHalver** [comment]
> Do the locked funds go to zero if you restart Alice?

My apologies, I confused Bob's account and Alice's account.
Everything is fine at this point.
Sorry for the annoyance.

**Comment by HoverHalver** [comment]
I created an offer to buy XMR with USD.
Everything seems ok at this point.
I just noticed that, in the portfolio tab, the enabled button for the offer, is red.
I would have though that green would seem more logical (?)

**Comment by woodser** [comment]
> I just noticed that, in the portfolio tab, the enabled button for the offer, is red.
> I would have though that green would seem more logical (?)

This is inherited from Bisq's UI which we are redesigning.

**Comment by HoverHalver** [comment]
> > I just noticed that, in the portfolio tab, the enabled button for the offer, is red.
> > I would have though that green would seem more logical (?)

> This is inherited from Bisq's UI which we are redesigning.

Indeed, but this seems to be a Bisq v1.6.2 GUI error,
because in Bisq v1.7.2 (the last), the enabled button is green when activated.

**Comment by HoverHalver** [comment]
I just completed successfully a XMR/USD trade.
Things seems to work nicely.
If we should test some specific points, please just tell it.

It's not very clear for me what are the differences between the current Haveno protocol (https://github.com/haveno-dex/haveno/blob/master/docs/trade_protocol/trade-protocol.md) used in this PR, and the Bisq protocol ?
Would it be possible to know what are the differences ?

**Comment by erciccione** [comment]
> Would it be possible to know what are the differences ?

The main difference is that Bisq uses 2/2 multisig instead of 2/3, but there are more. You can find more info here: https://github.com/haveno-dex/haveno/wiki/FAQ and here: https://bisq.wiki/Trading_rules

**Pull request merged**
